# Generated by Django 5.0.2 on 2024-02-26 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('username', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('emailid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('dob', models.CharField(default='', max_length=200)),
                ('mobileno', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(default='', max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.states'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('vaccine', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.states')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('dob', models.CharField(default='', max_length=25)),
                ('address', models.CharField(default='', max_length=150)),
                ('emailid', models.CharField(default='', max_length=100)),
                ('mobileno', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('photograph', models.ImageField(upload_to='static/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.city')),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='covid.states')),
            ],
        ),
    ]
