# Generated by Django 5.0.2 on 2024-02-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_doctors_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
